[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
ipython = "^8.29.0"
matplotlib = "^3.9.2"
torch = "2.0"
scikit-learn = "^1.5.2"
pandas = "^2.2.3"
numpy = "<2"
attrs = "^24.2.0"
pyarrow = "^18.0.0"
ruff = "^0.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
